// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    IconBi: exclamationCircleFill': typeof import('~icons/bi/exclamation-circle-fill')['default']
    'IconBi:exclamationCircleFill': typeof import('~icons/bi/exclamation-circle-fill')['default']
    IconClarity: timesLine': typeof import('~icons/clarity/times-line')['default']
    'IconClarity:timesCircleSolid': typeof import('~icons/clarity/times-circle-solid')['default']
    'IconClarity:timesLine': typeof import('~icons/clarity/times-line')['default']
    IconMdi: linkedin': typeof import('~icons/mdi/linkedin')['default']
    'IconMdi:arrowForward': typeof import('~icons/mdi/arrow-forward')['default']
    'IconMdi:checkCircle': typeof import('~icons/mdi/check-circle')['default']
    'IconMdi:email': typeof import('~icons/mdi/email')['default']
    'IconMdi:github': typeof import('~icons/mdi/github')['default']
    'IconMdi:linkedin': typeof import('~icons/mdi/linkedin')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }

}
